name: Bug
description: Reportar un defecto encontrado
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: ¿Qué está pasando?
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
    validations:
      required: true